name: Build & Push Docker Images to Docker Hub

on:
  push:
    branches: [master]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        component: [frontend, backend]

    steps:
      - name: â¬‡ï¸ Checkout code
        uses: actions/checkout@v3

      - name: ğŸ§  Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: ğŸ”‘ Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ğŸ“› Get short commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: ğŸ” Check for changes in ${{ matrix.component }}
        id: changes
        run: |
          if git diff --quiet HEAD~1 -- ${{ matrix.component }}; then
            echo "skip_build=true" >> $GITHUB_OUTPUT
          else
            echo "skip_build=false" >> $GITHUB_OUTPUT
          fi
      - name: debugging
        run: |
            ls -ltra
      - name: ğŸ› ï¸ Build & Push Docker image
        if: steps.changes.outputs.skip_build == 'false'
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.component }}
          file: ./${{ matrix.component }}/Dockerfile
          push: true
          tags: |
            akshunsinha/itransition:${{ matrix.component }}
            akshunsinha/itransition:${{ matrix.component }}-${{ steps.vars.outputs.sha_short }}
